#!/usr/bin/env bash
set -eu

echo "🔵 build"
source hooks/.config

echo "✅ Will build the following architectures: $(IFS=, ; echo "${build_architectures[@]}")"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

for arch in ${build_architectures[@]}; do
  echo "✅ building $arch"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

  LIDARR_ARCH=${lidarr_arch_map[${arch}]}
  LIDARR_RELEASE=$(curl -sX GET "https://api.github.com/repos/lidarr/Lidarr/releases" | jq -r '.[0] | .tag_name')
  lidarr_url=$(curl -s https://api.github.com/repos/lidarr/Lidarr/releases/tags/"${LIDARR_RELEASE}" | jq -r '.assets[].browser_download_url' | grep linux-musl-core-${LIDARR_ARCH})

  docker exec docker_daemon docker build \
    --squash \
    --platform=${docker_arch_map[${arch}]} \
    --build-arg BASE_IMAGE_PREFIX=${base_image_prefix_map[${arch}]} \
    --build-arg LIDARR_RELEASE=${LIDARR_RELEASE} \
    --build-arg lidarr_url=${lidarr_url} \
    --file /build/$DOCKERFILE_PATH \
    --tag "${IMAGE_NAME}-${arch}"  \
    /build
done

echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker image ls

trap "exit 1"          HUP INT PIPE QUIT TERM